In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import sys
import os
import re
sys.path.append(os.path.abspath(".."))
import src.dataset_selection as ds
import src.model_selection as md
import mlflow
import pandas as pd
import numpy as np

In [9]:
ds.log_models(
    '../data/final_datasets/datasets_linear_models',
    '../data/final_datasets/datasets_tree_based_models'
)

🏃 View run LinearRegression_conso_v2_linear at: http://localhost:5000/#/experiments/2/runs/3550bea284334b69b4ad4869160d88cd
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run Lasso_conso_v2_linear at: http://localhost:5000/#/experiments/2/runs/f5fca5a286864216b448c78974954dbb
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run Ridge_conso_v2_linear at: http://localhost:5000/#/experiments/2/runs/b2ae30e3be174be09535e24c9d40cb9e
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run ElasticNet_conso_v2_linear at: http://localhost:5000/#/experiments/2/runs/f0d621bdca3049309130525f2fad8e1b
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run LinearRegression_conso_v3_linear at: http://localhost:5000/#/experiments/2/runs/617590fb52434db3b5b2012294eee47c
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run Lasso_conso_v3_linear at: http://localhost:5000/#/experiments/2/runs/9313d4873c9a4597a59403352a3ddbda
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run Ridge_conso_v3_linear at: http://localhost:5000/#/experiments/2/runs/a5330be4f4c740b8826622b8a8418a32
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run ElasticNet_conso_v3_linear at: http://localhost:5000/#/experiments/2/runs/474e853cc6a846548f3489c6487e0675
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run LinearRegression_conso_v1_linear at: http://localhost:5000/#/experiments/2/runs/60672c9789f146c0a730355258d4ec2f
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run Lasso_conso_v1_linear at: http://localhost:5000/#/experiments/2/runs/03c3d42c416440c5938368208cea2cdd
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run Ridge_conso_v1_linear at: http://localhost:5000/#/experiments/2/runs/c2714d13f8444858a39a5d93b4152905
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run ElasticNet_conso_v1_linear at: http://localhost:5000/#/experiments/2/runs/63f05e88d8b042a88c134560338b2d72
🧪 View experiment at: http://localhost:5000/#/experiments/2
Linear Experiment successfully saved
🏃 View run GradientBoostingRegressor_conso_v2_tree at: http://localhost:5000/#/experiments/3/runs/d2fb33bedcd64d36878f632da3856105
🧪 View experiment at: http://localhost:5000/#/experiments/3
🏃 View run HistGradientBoostingRegressor_conso_v2_tree at: http://localhost:5000/#/experiments/3/runs/3acedb6e079846bab5131caf998cc30e
🧪 View experiment at: http://localhost:5000/#/experiments/3
🏃 View run RandomForestRegressor_conso_v2_tree at: http://localhost:5000/#/experiments/3/runs/d6be3da96c4540c0858db526358c82d7
🧪 View experiment at: http://localhost:5000/#/experiments/3
🏃 View run GradientBoostingRegressor_conso_v3_tree at: http://localhost:5000/#/experiments/3/runs/cc0ade3bd2ca4888aa33c6cd60e46dde
🧪 View experiment at: http://localhost:5000/#/experiments/3
🏃 View run HistGradientBoostingRegressor_conso_v3_tree at: http://localhost:5000/#/experiments/3/runs/bb8f738904334e4991b2dff7b816e2b0
🧪 View experiment at: http://localhost:5000/#/experiments/3
🏃 View run RandomForestRegressor_conso_v3_tree at: http://localhost:5000/#/experiments/3/runs/cee39c653fb642f9b74cef31b525d02f
🧪 View experiment at: http://localhost:5000/#/experiments/3
🏃 View run GradientBoostingRegressor_conso_v1_tree at: http://localhost:5000/#/experiments/3/runs/b89696214f384486b408e423e926ad9c
🧪 View experiment at: http://localhost:5000/#/experiments/3
🏃 View run HistGradientBoostingRegressor_conso_v1_tree at: http://localhost:5000/#/experiments/3/runs/cb59edcc250645d388e982e565d502f8
🧪 View experiment at: http://localhost:5000/#/experiments/3
🏃 View run RandomForestRegressor_conso_v1_tree at: http://localhost:5000/#/experiments/3/runs/c553f512417947158fd93f02c672fc70
🧪 View experiment at: http://localhost:5000/#/experiments/3
Trees Experiment successfully saved

After the analysis of the results, we'll keep the **dataset v3** because this one contains the best number of columns about the temperatures of the different French departments. Hence, it reduces the numner of dimensions and reduces overfitting too.
More over, we'll focus on **Ridge** (resists to overfitting on new data) and **HistGradientBoostingRegressor** (faster than a Random Forest during the training)

In [4]:
from sklearn.linear_model import Ridge
from sklearn.ensemble import HistGradientBoostingRegressor

In [11]:
md.log_models(
    '../data/final_datasets/datasets_linear_models/conso_v3_linear.parquet',
    '../data/final_datasets/datasets_tree_based_models/conso_v3_tree.parquet',
    Ridge(),
    HistGradientBoostingRegressor(),
    np.arange(0, 10, 1)    
)

2026/06/27 17:35:03 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.

🏃 View run Ridge_conso_v3_linear_horizon_0 at: http://localhost:5000/#/experiments/4/runs/a854f4765c694dac8453a3a9b526f86b
🧪 View experiment at: http://localhost:5000/#/experiments/4

2026/06/27 17:35:18 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.

🏃 View run Ridge_conso_v3_linear_horizon_1 at: http://localhost:5000/#/experiments/4/runs/055ab38270c747878755051fd553e5d8
🧪 View experiment at: http://localhost:5000/#/experiments/4

2026/06/27 17:35:33 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.

🏃 View run Ridge_conso_v3_linear_horizon_2 at: http://localhost:5000/#/experiments/4/runs/9a049db67eaa468faa4cab0c92b4303a
🧪 View experiment at: http://localhost:5000/#/experiments/4

2026/06/27 17:35:48 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.

🏃 View run Ridge_conso_v3_linear_horizon_3 at: http://localhost:5000/#/experiments/4/runs/0f43005836234878b188425003ab0904
🧪 View experiment at: http://localhost:5000/#/experiments/4

2026/06/27 17:36:02 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.

🏃 View run Ridge_conso_v3_linear_horizon_4 at: http://localhost:5000/#/experiments/4/runs/91fd32e3c5614c6ca53e04bd0fbd2b6e
🧪 View experiment at: http://localhost:5000/#/experiments/4

2026/06/27 17:36:17 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.

🏃 View run Ridge_conso_v3_linear_horizon_5 at: http://localhost:5000/#/experiments/4/runs/01ab6286bf4e494b967046d8cab7d59b
🧪 View experiment at: http://localhost:5000/#/experiments/4

2026/06/27 17:36:31 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.

🏃 View run Ridge_conso_v3_linear_horizon_6 at: http://localhost:5000/#/experiments/4/runs/6ff4fa056af24fcaab5e3357f981f44e
🧪 View experiment at: http://localhost:5000/#/experiments/4

2026/06/27 17:36:46 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.

🏃 View run Ridge_conso_v3_linear_horizon_7 at: http://localhost:5000/#/experiments/4/runs/f806be7a51f24fa2adbe6fec9f6390d5
🧪 View experiment at: http://localhost:5000/#/experiments/4

2026/06/27 17:37:00 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.

🏃 View run Ridge_conso_v3_linear_horizon_8 at: http://localhost:5000/#/experiments/4/runs/4ed36e712eb14fcfaf09e2991de0d140
🧪 View experiment at: http://localhost:5000/#/experiments/4

2026/06/27 17:37:15 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.

🏃 View run Ridge_conso_v3_linear_horizon_9 at: http://localhost:5000/#/experiments/4/runs/3ba37f8482cf493f8c88c70852ff0077
🧪 View experiment at: http://localhost:5000/#/experiments/4
Best models Experiment successfully saved

2026/06/27 17:38:50 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.

🏃 View run HistGradientBoostingRegressor_conso_v3_tree_horizon_0 at: http://localhost:5000/#/experiments/4/runs/2a60e39f74fa443fac7990a8bdab696e
🧪 View experiment at: http://localhost:5000/#/experiments/4

2026/06/27 17:40:23 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.

🏃 View run HistGradientBoostingRegressor_conso_v3_tree_horizon_1 at: http://localhost:5000/#/experiments/4/runs/707320d65fdf46bcbb7d806bbdd49311
🧪 View experiment at: http://localhost:5000/#/experiments/4

2026/06/27 17:41:57 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.

🏃 View run HistGradientBoostingRegressor_conso_v3_tree_horizon_2 at: http://localhost:5000/#/experiments/4/runs/e0795be2bb3b46f3bc2e921002ee9672
🧪 View experiment at: http://localhost:5000/#/experiments/4

2026/06/27 17:43:32 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.

🏃 View run HistGradientBoostingRegressor_conso_v3_tree_horizon_3 at: http://localhost:5000/#/experiments/4/runs/d4e501d3d2164d6d9d20053cefa6f92a
🧪 View experiment at: http://localhost:5000/#/experiments/4

2026/06/27 17:45:12 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.

🏃 View run HistGradientBoostingRegressor_conso_v3_tree_horizon_4 at: http://localhost:5000/#/experiments/4/runs/767d1cdd525c44a281ffe5d6d3025463
🧪 View experiment at: http://localhost:5000/#/experiments/4

2026/06/27 17:46:47 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.

🏃 View run HistGradientBoostingRegressor_conso_v3_tree_horizon_5 at: http://localhost:5000/#/experiments/4/runs/b4125c3ae7e04b69be7ba57a046f5ec9
🧪 View experiment at: http://localhost:5000/#/experiments/4

2026/06/27 17:48:22 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.

🏃 View run HistGradientBoostingRegressor_conso_v3_tree_horizon_6 at: http://localhost:5000/#/experiments/4/runs/6109de0a255342cea95411034c97dbbc
🧪 View experiment at: http://localhost:5000/#/experiments/4

2026/06/27 17:49:57 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.

🏃 View run HistGradientBoostingRegressor_conso_v3_tree_horizon_7 at: http://localhost:5000/#/experiments/4/runs/2d1fe06854924d8eb7799091ed0285a5
🧪 View experiment at: http://localhost:5000/#/experiments/4

2026/06/27 17:51:33 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.

🏃 View run HistGradientBoostingRegressor_conso_v3_tree_horizon_8 at: http://localhost:5000/#/experiments/4/runs/e7ad937d1e9e46949c4f9a8ae5b580ef
🧪 View experiment at: http://localhost:5000/#/experiments/4

2026/06/27 17:53:09 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.

🏃 View run HistGradientBoostingRegressor_conso_v3_tree_horizon_9 at: http://localhost:5000/#/experiments/4/runs/59f279959de54fe88d29b5e51035b791
🧪 View experiment at: http://localhost:5000/#/experiments/4
Best models Experiment successfully saved

In [6]:
mlflow.set_tracking_uri('http://localhost:5000')
experiment_name = "Best models Experiment"
experiment = mlflow.get_experiment_by_name(experiment_name)

In [7]:
runs = mlflow.search_runs(
    experiment_ids = [experiment.experiment_id],
    order_by = ['metrics.root_mean_squared_error ASC'],
    max_results=None
)

In [8]:
runs

,run_id,experiment_id,status,artifact_uri,start_time,end_time,metrics.mean absolute error,metrics.root mean squared error,metrics.mean squared error,metrics.r2 score,...,params.learning_rate,params.Ridge__tol,params.Ridge__alpha,tags.dataset,tags.mlflow.source.type,tags.mlflow.runName,tags.mlflow.user,tags.mlflow.source.name,tags.model,tags.horizon
0,59f279959de54fe88d29b5e51035b791,4,FINISHED,mlflow-artifacts:/4/59f279959de54fe88d29b5e510...,2026-06-27 15:53:08.517000+00:00,2026-06-27 15:53:20.443000+00:00,3057.850629,3778.859960,1.427978e+07,0.857045,...,0.01,None,None,conso_v3_tree,NOTEBOOK,HistGradientBoostingRegressor_conso_v3_tree_ho...,marwane,dataset_and_model_selection.ipynb,HistGradientBoostingRegressor,9
1,e7ad937d1e9e46949c4f9a8ae5b580ef,4,FINISHED,mlflow-artifacts:/4/e7ad937d1e9e46949c4f9a8ae5...,2026-06-27 15:51:33.180000+00:00,2026-06-27 15:51:45.144000+00:00,3059.678741,3781.766552,1.430176e+07,0.856816,...,0.01,None,None,conso_v3_tree,NOTEBOOK,HistGradientBoostingRegressor_conso_v3_tree_ho...,marwane,dataset_and_model_selection.ipynb,HistGradientBoostingRegressor,8
2,2d1fe06854924d8eb7799091ed0285a5,4,FINISHED,mlflow-artifacts:/4/2d1fe06854924d8eb7799091ed...,2026-06-27 15:49:57.472000+00:00,2026-06-27 15:50:09.349000+00:00,3058.282980,3780.034042,1.428866e+07,0.856940,...,0.01,None,None,conso_v3_tree,NOTEBOOK,HistGradientBoostingRegressor_conso_v3_tree_ho...,marwane,dataset_and_model_selection.ipynb,HistGradientBoostingRegressor,7
3,6109de0a255342cea95411034c97dbbc,4,FINISHED,mlflow-artifacts:/4/6109de0a255342cea95411034c...,2026-06-27 15:48:22.437000+00:00,2026-06-27 15:48:34.317000+00:00,3055.718274,3777.848567,1.427214e+07,0.857097,...,0.01,None,None,conso_v3_tree,NOTEBOOK,HistGradientBoostingRegressor_conso_v3_tree_ho...,marwane,dataset_and_model_selection.ipynb,HistGradientBoostingRegressor,6
4,b4125c3ae7e04b69be7ba57a046f5ec9,4,FINISHED,mlflow-artifacts:/4/b4125c3ae7e04b69be7ba57a04...,2026-06-27 15:46:47.347000+00:00,2026-06-27 15:46:59.269000+00:00,3052.624482,3775.129290,1.425160e+07,0.857295,...,0.01,None,None,conso_v3_tree,NOTEBOOK,HistGradientBoostingRegressor_conso_v3_tree_ho...,marwane,dataset_and_model_selection.ipynb,HistGradientBoostingRegressor,5
5,767d1cdd525c44a281ffe5d6d3025463,4,FINISHED,mlflow-artifacts:/4/767d1cdd525c44a281ffe5d6d3...,2026-06-27 15:45:11.567000+00:00,2026-06-27 15:45:23.428000+00:00,3057.434288,3778.818680,1.427947e+07,0.857009,...,0.01,None,None,conso_v3_tree,NOTEBOOK,HistGradientBoostingRegressor_conso_v3_tree_ho...,marwane,dataset_and_model_selection.ipynb,HistGradientBoostingRegressor,4
6,d4e501d3d2164d6d9d20053cefa6f92a,4,FINISHED,mlflow-artifacts:/4/d4e501d3d2164d6d9d20053cef...,2026-06-27 15:43:31.565000+00:00,2026-06-27 15:43:46.794000+00:00,3056.839972,3777.694840,1.427098e+07,0.857086,...,0.01,None,None,conso_v3_tree,NOTEBOOK,HistGradientBoostingRegressor_conso_v3_tree_ho...,marwane,dataset_and_model_selection.ipynb,HistGradientBoostingRegressor,3
7,e0795be2bb3b46f3bc2e921002ee9672,4,FINISHED,mlflow-artifacts:/4/e0795be2bb3b46f3bc2e921002...,2026-06-27 15:41:57.296000+00:00,2026-06-27 15:42:09.051000+00:00,3059.634683,3782.763965,1.430930e+07,0.856695,...,0.01,None,None,conso_v3_tree,NOTEBOOK,HistGradientBoostingRegressor_conso_v3_tree_ho...,marwane,dataset_and_model_selection.ipynb,HistGradientBoostingRegressor,2
8,707320d65fdf46bcbb7d806bbdd49311,4,FINISHED,mlflow-artifacts:/4/707320d65fdf46bcbb7d806bbd...,2026-06-27 15:40:23.335000+00:00,2026-06-27 15:40:35.292000+00:00,3055.595536,3774.948664,1.425024e+07,0.857281,...,0.01,None,None,conso_v3_tree,NOTEBOOK,HistGradientBoostingRegressor_conso_v3_tree_ho...,marwane,dataset_and_model_selection.ipynb,HistGradientBoostingRegressor,1
9,2a60e39f74fa443fac7990a8bdab696e,4,FINISHED,mlflow-artifacts:/4/2a60e39f74fa443fac7990a8bd...,2026-06-27 15:38:50.266000+00:00,2026-06-27 15:39:02.194000+00:00,3037.504075,3753.553092,1.408916e+07,0.858888,...,0.01,None,None,conso_v3_tree,NOTEBOOK,HistGradientBoostingRegressor_conso_v3_tree_ho...,marwane,dataset_and_model_selection.ipynb,HistGradientBoostingRegressor,0
10,3ba37f8482cf493f8c88c70852ff0077,4,FINISHED,mlflow-artifacts:/4/3ba37f8482cf493f8c88c70852...,2026-06-27 15:37:14.738000+00:00,2026-06-27 15:37:26.424000+00:00,476.962780,620.470818,3.849840e+05,0.996146,...,None,0.001,0.1,conso_v3_linear,NOTEBOOK,Ridge_conso_v3_linear_horizon_9,marwane,dataset_and_model_selection.ipynb,Ridge,9
11,4ed36e712eb14fcfaf09e2991de0d140,4,FINISHED,mlflow-artifacts:/4/4ed36e712eb14fcfaf09e2991d...,2026-06-27 15:37:00.129000+00:00,2026-06-27 15:37:11.811000+00:00,483.600012,628.351293,3.948253e+05,0.996047,...,None,0.001,0.1,conso_v3_linear,NOTEBOOK,Ridge_conso_v3_linear_horizon_8,marwane,dataset_and_model_selection.ipynb,Ridge,8
12,f806be7a51f24fa2adbe6fec9f6390d5,4,FINISHED,mlflow-artifacts:/4/f806be7a51f24fa2adbe6fec9f...,2026-06-27 15:36:45.608000+00:00,2026-06-27 15:36:57.217000+00:00,478.757521,621.620251,3.864117e+05,0.996131,...,None,0.001,0.1,conso_v3_linear,NOTEBOOK,Ridge_conso_v3_linear_horizon_7,marwane,dataset_and_model_selection.ipynb,Ridge,7
13,6ff4fa056af24fcaab5e3357f981f44e,4,FINISHED,mlflow-artifacts:/4/6ff4fa056af24fcaab5e3357f9...,2026-06-27 15:36:31.088000+00:00,2026-06-27 15:36:42.799000+00:00,471.871190,618.959379,3.831107e+05,0.996164,...,None,0.001,0.1,conso_v3_linear,NOTEBOOK,Ridge_conso_v3_linear_horizon_6,marwane,dataset_and_model_selection.ipynb,Ridge,6
14,01ab6286bf4e494b967046d8cab7d59b,4,FINISHED,mlflow-artifacts:/4/01ab6286bf4e494b967046d8ca...,2026-06-27 15:36:16.672000+00:00,2026-06-27 15:36:28.314000+00:00,463.354062,603.820125,3.645987e+05,0.996349,...,None,0.001,0.1,conso_v3_linear,NOTEBOOK,Ridge_conso_v3_linear_horizon_5,marwane,dataset_and_model_selection.ipynb,Ridge,5
15,91fd32e3c5614c6ca53e04bd0fbd2b6e,4,FINISHED,mlflow-artifacts:/4/91fd32e3c5614c6ca53e04bd0f...,2026-06-27 15:36:02.324000+00:00,2026-06-27 15:36:13.911000+00:00,461.968571,605.361263,3.664623e+05,0.996330,...,None,0.001,0.1,conso_v3_linear,NOTEBOOK,Ridge_conso_v3_linear_horizon_4,marwane,dataset_and_model_selection.ipynb,Ridge,4
16,0f43005836234878b188425003ab0904,4,FINISHED,mlflow-artifacts:/4/0f43005836234878b188425003...,2026-06-27 15:35:48.019000+00:00,2026-06-27 15:35:59.582000+00:00,441.986012,581.742006,3.384238e+05,0.996611,...,None,0.001,0.1,conso_v3_linear,NOTEBOOK,Ridge_conso_v3_linear_horizon_3,marwane,dataset_and_model_selection.ipynb,Ridge,3
17,9a049db67eaa468faa4cab0c92b4303a,4,FINISHED,mlflow-artifacts:/4/9a049db67eaa468faa4cab0c92...,2026-06-27 15:35:33.240000+00:00,2026-06-27 15:35:45.246000+00:00,416.958345,558.376209,3.117840e+05,0.996878,...,None,0.001,0.1,conso_v3_linear,NOTEBOOK,Ridge_conso_v3_linear_horizon_2,marwane,dataset_and_model_selection.ipynb,Ridge,2
18,055ab38270c747878755051fd553e5d8,4,FINISHED,mlflow-artifacts:/4/055ab38270c747878755051fd5...,2026-06-27 15:35:17.531000+00:00,2026-06-27 15:35:30.345000+00:00,360.319049,490.062999,2.401617e+05,0.997595,...,None,0.001,0.1,conso_v3_linear,NOTEBOOK,Ridge_conso_v3_linear_horizon_1,marwane,dataset_and_model_selection.ipynb,Ridge,1
19,a854f4765c694dac8453a3a9b526f86b,4,FINISHED,mlflow-artifacts:/4/a854f4765c694dac8453a3a9b5...,2026-06-27 15:35:02.583000+00:00,2026-06-27 15:35:14.550000+00:00,242.241649,343.854663,1.182360e+05,0.998816,...,None,0.001,0.1,conso_v3_linear,NOTEBOOK,Ridge_conso_v3_linear_horizon_0,marwane,dataset_and_model_selection.ipynb,Ridge,0

In [161]:
best_models = runs.sort_values(by="metrics.mean squared error")

#### We keep the estimator that performs the best for horizon = 9 (the furthest horizon) because it will, naturally, perform better for the closest horizons

In [91]:
estimator1 = "Ridge"
dataset_name1 = "conso_v3_linear"
h = 9

estimator2 = "HistGradientBoostingRegressor"
dataset_name2 = "conso_v3_tree"

query1 = best_models[
    (best_models["tags.model"] == f"{estimator1}") &
    (best_models["tags.mlflow.runName"] == f"{estimator1}_{dataset_name1}_horizon_{h}")
    ]

score1 = query1["metrics.mean squared error"].iloc[0]

In [92]:
score1

np.float64(384984.03544540494)

In [93]:
query2 = best_models[
    (best_models["tags.model"] == f"{estimator2}") &
    (best_models["tags.mlflow.runName"] == f"{estimator2}_{dataset_name2}_horizon_{h}")
    ]

score2 = query2["metrics.mean squared error"].iloc[0]

In [102]:
best_estimator = None
if score1 < score2 : 
    best_estimator = query1["tags.model"].unique()[0]
else : 
    best_estimator = query2["tags.model"].unique()[0]

In [103]:
best_estimator

'Ridge'

In [151]:
best_runs = best_models[best_models["tags.model"] == best_estimator]

In [152]:
best_runs

,run_id,experiment_id,status,artifact_uri,start_time,end_time,metrics.r2 score,metrics.CV root mean squared error,metrics.mean absolute error,metrics.mean squared error,...,params.learning_rate,params.Ridge__tol,params.Ridge__alpha,tags.mlflow.user,tags.dataset,tags.horizon,tags.mlflow.runName,tags.mlflow.source.name,tags.mlflow.source.type,tags.model
19,a854f4765c694dac8453a3a9b526f86b,4,FINISHED,mlflow-artifacts:/4/a854f4765c694dac8453a3a9b5...,2026-06-27 15:35:02.583000+00:00,2026-06-27 15:35:14.550000+00:00,0.998816,379.188756,242.241649,118236.029060,...,None,0.001,0.1,marwane,conso_v3_linear,0,Ridge_conso_v3_linear_horizon_0,dataset_and_model_selection.ipynb,NOTEBOOK,Ridge
18,055ab38270c747878755051fd553e5d8,4,FINISHED,mlflow-artifacts:/4/055ab38270c747878755051fd5...,2026-06-27 15:35:17.531000+00:00,2026-06-27 15:35:30.345000+00:00,0.997595,533.845889,360.319049,240161.742511,...,None,0.001,0.1,marwane,conso_v3_linear,1,Ridge_conso_v3_linear_horizon_1,dataset_and_model_selection.ipynb,NOTEBOOK,Ridge
17,9a049db67eaa468faa4cab0c92b4303a,4,FINISHED,mlflow-artifacts:/4/9a049db67eaa468faa4cab0c92...,2026-06-27 15:35:33.240000+00:00,2026-06-27 15:35:45.246000+00:00,0.996878,611.394962,416.958345,311783.991142,...,None,0.001,0.1,marwane,conso_v3_linear,2,Ridge_conso_v3_linear_horizon_2,dataset_and_model_selection.ipynb,NOTEBOOK,Ridge
16,0f43005836234878b188425003ab0904,4,FINISHED,mlflow-artifacts:/4/0f43005836234878b188425003...,2026-06-27 15:35:48.019000+00:00,2026-06-27 15:35:59.582000+00:00,0.996611,640.966305,441.986012,338423.761195,...,None,0.001,0.1,marwane,conso_v3_linear,3,Ridge_conso_v3_linear_horizon_3,dataset_and_model_selection.ipynb,NOTEBOOK,Ridge
14,01ab6286bf4e494b967046d8cab7d59b,4,FINISHED,mlflow-artifacts:/4/01ab6286bf4e494b967046d8ca...,2026-06-27 15:36:16.672000+00:00,2026-06-27 15:36:28.314000+00:00,0.996349,672.961154,463.354062,364598.743245,...,None,0.001,0.1,marwane,conso_v3_linear,5,Ridge_conso_v3_linear_horizon_5,dataset_and_model_selection.ipynb,NOTEBOOK,Ridge
15,91fd32e3c5614c6ca53e04bd0fbd2b6e,4,FINISHED,mlflow-artifacts:/4/91fd32e3c5614c6ca53e04bd0f...,2026-06-27 15:36:02.324000+00:00,2026-06-27 15:36:13.911000+00:00,0.996330,661.082215,461.968571,366462.258190,...,None,0.001,0.1,marwane,conso_v3_linear,4,Ridge_conso_v3_linear_horizon_4,dataset_and_model_selection.ipynb,NOTEBOOK,Ridge
13,6ff4fa056af24fcaab5e3357f981f44e,4,FINISHED,mlflow-artifacts:/4/6ff4fa056af24fcaab5e3357f9...,2026-06-27 15:36:31.088000+00:00,2026-06-27 15:36:42.799000+00:00,0.996164,686.016426,471.871190,383110.712971,...,None,0.001,0.1,marwane,conso_v3_linear,6,Ridge_conso_v3_linear_horizon_6,dataset_and_model_selection.ipynb,NOTEBOOK,Ridge
10,3ba37f8482cf493f8c88c70852ff0077,4,FINISHED,mlflow-artifacts:/4/3ba37f8482cf493f8c88c70852...,2026-06-27 15:37:14.738000+00:00,2026-06-27 15:37:26.424000+00:00,0.996146,687.096876,476.962780,384984.035445,...,None,0.001,0.1,marwane,conso_v3_linear,9,Ridge_conso_v3_linear_horizon_9,dataset_and_model_selection.ipynb,NOTEBOOK,Ridge
12,f806be7a51f24fa2adbe6fec9f6390d5,4,FINISHED,mlflow-artifacts:/4/f806be7a51f24fa2adbe6fec9f...,2026-06-27 15:36:45.608000+00:00,2026-06-27 15:36:57.217000+00:00,0.996131,685.364669,478.757521,386411.736873,...,None,0.001,0.1,marwane,conso_v3_linear,7,Ridge_conso_v3_linear_horizon_7,dataset_and_model_selection.ipynb,NOTEBOOK,Ridge
11,4ed36e712eb14fcfaf09e2991de0d140,4,FINISHED,mlflow-artifacts:/4/4ed36e712eb14fcfaf09e2991d...,2026-06-27 15:37:00.129000+00:00,2026-06-27 15:37:11.811000+00:00,0.996047,692.552904,483.600012,394825.347734,...,None,0.001,0.1,marwane,conso_v3_linear,8,Ridge_conso_v3_linear_horizon_8,dataset_and_model_selection.ipynb,NOTEBOOK,Ridge

In [170]:
query1 = best_models[
    (best_models["tags.model"] == estimator2) &
    (best_models["tags.dataset"] == dataset_name2) &
    (best_models["tags.horizon"].astype(str) == str(h))
]

query1

,run_id,experiment_id,status,artifact_uri,start_time,end_time,metrics.r2 score,metrics.CV root mean squared error,metrics.mean absolute error,metrics.mean squared error,...,params.learning_rate,params.Ridge__tol,params.Ridge__alpha,tags.mlflow.user,tags.dataset,tags.horizon,tags.mlflow.runName,tags.mlflow.source.name,tags.mlflow.source.type,tags.model
0,59f279959de54fe88d29b5e51035b791,4,FINISHED,mlflow-artifacts:/4/59f279959de54fe88d29b5e510...,2026-06-27 15:53:08.517000+00:00,2026-06-27 15:53:20.443000+00:00,0.857045,4313.109759,3057.850629,1.427978e+07,...,0.01,None,None,marwane,conso_v3_tree,9,HistGradientBoostingRegressor_conso_v3_tree_ho...,dataset_and_model_selection.ipynb,NOTEBOOK,HistGradientBoostingRegressor

In [11]:
experiment_name = "Best models Experiment"
best_estimator, dict_models = md.dump_model_from_mlflow(
    experiment_name, 
    "../artifacts/model_artifacts"
)

Ridge models have been successfully saved in ../artifacts/model_artifacts/Ridge_2026-06-28_17-02-54